apiVersion: v1
kind: Service
metadata:
  name: hazelcast-client-service
spec:
  selector:
    app: hazelcast-client
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
  type: LoadBalancer