apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: hazelcast-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast-cluster
    spec:
      containers:
        - name: discovery-server
          image: gcr.io/hazelcast-cluster/discovery-server:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 8761