server:
  port: 8762
spring:
  application:
    name: hazelcast-server-1
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    eureka-connection-idle-timeout-seconds: 45
  instance:
    appname: hazelcast-server
    virtual-host-name: hazelcast-server
    ip-address: ${spring.cloud.client.ip-address}
    hostname: ${spring.cloud.client.ip-address}
    non-secure-port: 8762
    preferIpAddress: true
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
    home-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/env
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30

endpoints:
  health.sensitive: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full