apiVersion: v1
kind: Service
metadata:
  name: hazelcast-server-service
spec:
  selector:
    app: hazelcast-server
  ports:
    - protocol: TCP
      port: 8762
      targetPort: 8762
  type: LoadBalancer