server:
  port: 8763
spring:
  application:
    name: hazelcast-server-2
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
    home-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/env
    appname: hazelcast-server
    virtual-host-name: hazelcast-server


endpoints:
  health.sensitive: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
